version: "3"
services:
  ftunes_api:
    build: .
    container_name: ftunes_api
    networks:
      - web
    env_file:
      - .env
    restart: always
    labels:
      caddy: http://fta.djara.dev
      caddy.reverse_proxy: "{{upstreams 3000}}"

networks: 
  web:
    external: true
